create table public.videos (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  video_id text null,
  title text null,
  description text null,
  summary text null,
  keypoints text[] null,
  actionable - tasks text[] null,
  quotes text[] null,
  tags text[] null,
  channel text null,
  transcript text null,
  constraint videos_pkey primary key (id)
) TABLESPACE pg_default;